### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by apprehensions** [ehawkvu/kiss-xorg#153]
Please @ehawkvu i'm asking you to drop useless, unused packages with no recursive dependencies in community.

Here are a list of packages that no packages dependent on them, and are outdated:

* bdftopcf
* brownout
* chromium
* godot
* gst-plugins-base
* gtk+2
* i3
* inkscape
* netsurf-gtk3
* palemoon
* qt5-x11extras
* sct
* winetricks
* coin
* freecad
* gnumeric
* gtk+4
* kicad
* libmedc
* nyxt
* python-pivy
* qpwgraph
* qt6
* sxcs
* x11up
* xcalc
* xcircuit

these should only be used as a point of reference, because there is way too many packages on here.

for example, i believe qt and xfce should be split into their own repositories, much like kiss-kde.

**Comment by ehawkvu** [comment]
@apprehensions did you even look at the list of packages that you just posted?

Because the flaw with your *methodology* is that you are going to pick up packages which are more than likely end-user applications (see chromium, kicad, qpwgraph, gnumeric, etc). 

Other packages in that list I require for use over at kiss-java-boot, which make **more** sense to package here, since they are well X11 releated. gtk+2 would be such a package, and I figured that if I **need** it for java then *why not* package it for xorg?

Also, I know that this topic has come up multiple times before with you particularly, but why do you want the package volume to be reduced? It's not like you are maintaining the vast majority of them. Is it a cleanliness issue?  A worry about how many packages it is? Do you just want `community/` to be `rm`'d? I'm just confused as to your motivation on this issue.

Also, kiss-kde is dead, hence why I've attempted to resurrect it in [ehawkvu/kiss-repos](https://github.com/ehawkvu/kiss-repos)

XFCE has it's own repo - see the `xfce/` **repo** here. 

I'd be fine splitting out the qt packages to a common repo (again look at kiss-repos) so that way the wayland people and us can use the packages via submodules. You'd have to sell community on that approach though, which is unlikely.

**Comment by apprehensions** [comment]
I see, It is just bothersome to have many packages that are still going to be outdated and are for niche usecases, because gtk+2 itself is rather legacy and out of date, and if its required only for java, then it would make more sense to put it in that respective repository.

But, as seeing you still wish to maintain such packages, i guess i dont have much of a choice. Just the fact that this is a KISS repository and has an enormous amount of packages is sort of unsettling.

**Comment by ehawkvu** [comment]
For context on volume of packages:

kiss-xorg ~ `ls */ | wc -l` - 392

[community](https://github.com/kiss-community/community) ~ `ls */ | wc -l` - 358

While it looks like xorg is large in comparison, here's the breakdown:

* community/ - 229
* extra/ - 23
* games/ - 19
* kde1/ - 7
* testing/ - 2
* xfce4/ - 18
* xorg/ - 74
* xwayland/ - 5
